version: '3.8'

services:
  # 后端服务
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: heartbeat-backend
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./a_love_story.db:/app/a_love_story.db
    environment:
      - DATABASE_URL=sqlite:///./a_love_story.db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    restart: unless-stopped
    networks:
      - heartbeat-network

  # 前端服务
  frontend:
    build:
      context: ./heartbeat-frontend
      dockerfile: Dockerfile
    container_name: heartbeat-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - heartbeat-network

  # Nginx 反向代理（可选，用于更复杂的部署）
  nginx:
    image: nginx:alpine
    container_name: heartbeat-nginx
    ports:
      - "443:443"
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - heartbeat-network
    profiles:
      - production

networks:
  heartbeat-network:
    driver: bridge

volumes:
  static_files:
  database_data: